### ISSUE TITLE
label.replace is not a function

### ISSUE THREAD

**Issue by musab** [remcohaszing/monaco-yaml#117]
Running into this error

```
TypeError: label.replace is not a function
    at Object.add (/projects/_next/static/083ffcf6caefb8bf132b88c985d2dc95.worker.js:7881:25)
    at YAMLCompletion.JSONCompletion2.addEnumValueCompletions (/projects/_next/static/083ffcf6caefb8bf132b88c985d2dc95.worker.js:4094:19)
    at YAMLCompletion.JSONCompletion2.addSchemaValueCompletions (/projects/_next/static/083ffcf6caefb8bf132b88c985d2dc95.worker.js:3972:12)
    at YAMLCompletion.addSchemaValueCompletions (/projects/_next/static/083ffcf6caefb8bf132b88c985d2dc95.worker.js:8133:11)
    at /projects/_next/static/083ffcf6caefb8bf132b88c985d2dc95.worker.js:8111:20
    at Array.forEach (<anonymous>)
    at YAMLCompletion.getValueCompletions (/projects/_next/static/083ffcf6caefb8bf132b88c985d2dc95.worker.js:8069:23)
    at /projects/_next/static/083ffcf6caefb8bf132b88c985d2dc95.worker.js:7969:14
(Most recent call first)
```

Reproduction steps: 

1. Open https://monaco-yaml.js.org/
2. Switch to CircleCI config.yml
3. Start typing `version: 2.1` on line 1

![image](https://user-images.githubusercontent.com/34455928/134365734-94ab9086-4cc2-4b84-92e5-5dd017fb2c53.png)

**Comment by remcohaszing** [comment]
Thanks for reporting this!

This is an upstream issue. I reported it in https://github.com/redhat-developer/yaml-language-server/issues/547.

**Comment by musab** [comment]
@remcohaszing I noticed the fix has now been merged https://github.com/redhat-developer/yaml-language-server/pull/549 — will a future update include this fix?
